repos:
  - repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.0.5
    hooks:
      - id: search-and-replace
        name: Check for PII
        files: ^resume.*.yaml$

fail_fast: true
